language: node_js

node_js:
  - 8

cache:
  directories:
  - node_modules
  - $HOME/.yarn-cache

install:
  - yarn install

script:
  - travis_retry npm test

notifications:
  webhooks: https://api.kotori.love/github/hook/travis
